- id: checkpatch.pl
  name: run checkpatch.pl
  description: >
    Check whether the code follows kernel coding style.
  entry: pre_commit_hooks/do-checkpatch
  args: [-v]
  language: script
- id: check-file-execute-permission
  name: file execute permission check
  entry: file must not have executable permission.
  language: fail
  types: [executable]
- id: convert-to-junit
  name: convert log to junit format
  description: >
    Generate junit format from text log file
  entry: pre_commit_hooks/convert-to-junit
  args: [-i, log.txt, -o, out.xml]
  language: script
  pass_filenames: false
