- id: checkpatch.pl
  name: run checkpatch.pl
  description: >
    Check whether the code follows kernel coding style.
  entry: pre_commit_hooks/do-checkpatch
  args: [-v]
  language: script
  pass_filenames: false
- id: check-file-execute-permission
  name: file execute permission check
  entry: file must not have executable permission.
  language: fail
  types: [executable]
